# Generated by Django 6.0.5 on 2026-07-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nom')),
                ('event_type', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('wedding_anniversary', 'Anniversaire de mariage'), ('corporate', 'Corporate'), ('graduation', 'Remise de diplôme'), ('other', 'Autre')], db_index=True, max_length=30, verbose_name="type d'événement")),
                ('event_type_other', models.CharField(blank=True, max_length=100, verbose_name='autre type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='heure')),
                ('location', models.CharField(max_length=500, verbose_name='lieu')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='lien Google Maps')),
                ('dress_code', models.CharField(blank=True, max_length=200, verbose_name='code vestimentaire')),
                ('drink_options', models.JSONField(default=list, verbose_name='options de boissons')),
                ('reminder_message', models.TextField(blank=True, verbose_name='message de rappel')),
                ('sender_email', models.EmailField(default='noreply@kbfeven.com', max_length=254, verbose_name='email expéditeur')),
                ('invitation_message', models.TextField(blank=True, help_text='Message personnalisé pour l\'invitation (ex: "Nous avons le plaisir de vous inviter à notre mariage...")', verbose_name="message d'invitation")),
                ('allow_other_drinks', models.BooleanField(default=True, help_text='Permettre aux invités de saisir une boisson personnalisée dans le formulaire RSVP', verbose_name='autoriser "Autre" boisson')),
                ('has_tables', models.BooleanField(default=False, help_text='Cocher si cet événement nécessite une gestion des tables', verbose_name='nécessite des tables')),
                ('groom_name', models.CharField(blank=True, help_text="Nom complet de l'époux (ex: Daniel Galleg)", max_length=100, null=True, verbose_name="nom de l'époux")),
                ('bride_name', models.CharField(blank=True, help_text="Nom complet de l'épouse (ex: Cahaya Dewi)", max_length=100, null=True, verbose_name="nom de l'épouse")),
                ('celebrant_name', models.CharField(blank=True, help_text='Nom de la personne célébrée (ex: John Doe)', max_length=100, null=True, verbose_name='nom du célébrant')),
                ('celebrant_title', models.CharField(blank=True, help_text='Roi, Reine, Prince, Princesse, etc.', max_length=50, null=True, verbose_name='titre du célébrant')),
                ('rsvp_token', models.CharField(blank=True, db_index=True, max_length=36, unique=True, verbose_name='token RSVP')),
                ('coorganizer_token', models.CharField(blank=True, db_index=True, max_length=36, unique=True, verbose_name='token co-organisateur')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payé')),
                ('max_guests_allowed', models.PositiveIntegerField(default=400, verbose_name="nombre max d'invités")),
                ('max_collaborators_allowed', models.PositiveIntegerField(default=5, verbose_name='nombre max de co-organisateurs')),
                ('coorganizer_short_code', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, verbose_name='code court co-organisateur')),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='event_photos/%Y/%m/%d/', verbose_name="photo de l'événement")),
                ('event_color', models.CharField(default='#8B5CF6', help_text='Code couleur hexadécimal (ex: #8B5CF6)', max_length=20, verbose_name="couleur de l'invitation")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('main_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='organisateur principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('invitation_token', models.CharField(db_index=True, max_length=50, unique=True, verbose_name="token d'invitation")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('can_scan', models.BooleanField(default=False, verbose_name='peut scanner')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invité le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepté le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.event', verbose_name='événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'co-organisateur',
                'verbose_name_plural': 'co-organisateurs',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('name', models.CharField(help_text="Nom de la table (ex: Table d'honneur, Table 1, etc.)", max_length=100, verbose_name='nom de la table')),
                ('capacity', models.PositiveIntegerField(default=8, help_text='Nombre maximum de personnes par table', verbose_name='capacité')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='events.event', verbose_name='événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['main_organizer', 'event_type'], name='events_even_main_or_13e054_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['main_organizer', 'is_active'], name='events_even_main_or_ec6cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['main_organizer', 'is_published'], name='events_even_main_or_d9cc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'event_type'], name='events_even_date_5a7630_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['rsvp_token'], name='events_even_rsvp_to_4ba207_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['coorganizer_token'], name='events_even_coorgan_5248ee_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcollaborator',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_24e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcollaborator',
            index=models.Index(fields=['user', 'status'], name='events_even_user_id_4d30e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcollaborator',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['event', 'id'], name='events_tabl_event_i_4c2e60_idx'),
        ),
    ]
