# Generated by Django 6.0.5 on 2026-07-17 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('will_attend', models.BooleanField(db_index=True, default=True, verbose_name='sera présent(e)')),
                ('number_of_guests', models.PositiveIntegerField(default=1, verbose_name='nombre de personnes')),
                ('is_accompanied', models.BooleanField(default=False, verbose_name='accompagné(e)')),
                ('companion_name', models.CharField(blank=True, max_length=200, verbose_name="nom de l'accompagnant")),
                ('companion_first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom accompagnant')),
                ('companion_last_name', models.CharField(blank=True, max_length=100, verbose_name='nom accompagnant')),
                ('drink_choice', models.CharField(blank=True, choices=[('vin', 'Vin'), ('biere', 'Bière'), ('soft', 'Soft'), ('jus', 'Jus'), ('eau', 'Eau'), ('other', 'Autre')], max_length=20, verbose_name='choix de boisson')),
                ('drink_other', models.CharField(blank=True, max_length=100, verbose_name='autre boisson')),
                ('companion_drink_choice', models.CharField(blank=True, choices=[('vin', 'Vin'), ('biere', 'Bière'), ('soft', 'Soft'), ('jus', 'Jus'), ('eau', 'Eau'), ('other', 'Autre')], max_length=20, verbose_name='boisson accompagnant')),
                ('companion_drink_other', models.CharField(blank=True, max_length=100, verbose_name='autre boisson accompagnant')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='végétarien/végétalien')),
                ('special_notes', models.TextField(blank=True, verbose_name='notes spéciales')),
                ('verification_status', models.CharField(choices=[('verified', 'Vérifié - Invité officiel'), ('unverified', 'Non vérifié')], db_index=True, default='unverified', max_length=20, verbose_name='statut de vérification')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='soumis le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='rappel envoyé')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le')),
                ('invitation_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token invitation')),
                ('checkin_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="heure d'arrivée")),
                ('is_excess', models.BooleanField(default=False, verbose_name='excédent')),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=5, null=True, unique=True, verbose_name='code court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.event', verbose_name='événement')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='events.table', verbose_name='table assignée')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': "réponse d'invité",
                'verbose_name_plural': 'réponses des invités',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['event', 'verification_status'], name='guests_gues_event_i_c7c89f_idx'), models.Index(fields=['event', 'will_attend'], name='guests_gues_event_i_882136_idx'), models.Index(fields=['event', 'checkin_time'], name='guests_gues_event_i_273c5e_idx'), models.Index(fields=['event', 'table'], name='guests_gues_event_i_3a30c3_idx'), models.Index(fields=['short_code'], name='guests_gues_short_c_5e4013_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='InvitedGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='nom')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='events.event', verbose_name='événement')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_guests', to='events.table', verbose_name='table assignée')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'invité pré-enregistré',
                'verbose_name_plural': 'invités pré-enregistrés',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['event', 'last_name', 'first_name'], name='guests_invi_event_i_60e0da_idx'), models.Index(fields=['email'], name='guests_invi_email_71bf71_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
