# Generated by Django 6.0.5 on 2026-07-17 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitedguest',
            name='guests_invi_email_71bf71_idx',
        ),
        migrations.AlterUniqueTogether(
            name='guestresponse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invitedguest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='guestresponse',
            name='drink_choice',
            field=models.CharField(blank=True, choices=[('vin', 'Vin'), ('biere', 'Bière'), ('soft', 'Soft'), ('jus', 'Jus'), ('eau', 'Eau'), ('other', 'Autre')], db_index=True, max_length=20, verbose_name='choix de boisson'),
        ),
        migrations.AlterField(
            model_name='guestresponse',
            name='is_accompanied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='accompagné(e)'),
        ),
        migrations.AlterField(
            model_name='invitedguest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AddIndex(
            model_name='guestresponse',
            index=models.Index(fields=['event', 'is_deleted'], name='guests_gues_event_i_74f4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='guestresponse',
            index=models.Index(fields=['first_name', 'last_name'], name='guests_gues_first_n_a93d60_idx'),
        ),
        migrations.AddIndex(
            model_name='guestresponse',
            index=models.Index(fields=['event', 'verification_status', 'will_attend'], name='guests_gues_event_i_9fc4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='invitedguest',
            index=models.Index(fields=['event', 'email'], name='guests_invi_event_i_7e49d0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitedguest',
            index=models.Index(fields=['event', 'is_deleted'], name='guests_invi_event_i_598e87_idx'),
        ),
        migrations.AddIndex(
            model_name='invitedguest',
            index=models.Index(fields=['event', 'table'], name='guests_invi_event_i_475e36_idx'),
        ),
    ]
