# Generated by Django 6.0.5 on 2026-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0002_remove_invitedguest_guests_invi_email_71bf71_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guestresponse',
            name='guests_gues_first_n_a93d60_idx',
        ),
        migrations.AlterField(
            model_name='guestresponse',
            name='drink_choice',
            field=models.CharField(blank=True, choices=[('vin', 'Vin'), ('biere', 'Bière'), ('soft', 'Soft'), ('jus', 'Jus'), ('eau', 'Eau'), ('other', 'Autre')], max_length=20, verbose_name='choix de boisson'),
        ),
        migrations.AlterField(
            model_name='guestresponse',
            name='is_accompanied',
            field=models.BooleanField(default=False, verbose_name='accompagné(e)'),
        ),
        migrations.AlterUniqueTogether(
            name='guestresponse',
            unique_together={('event', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='invitedguest',
            unique_together={('event', 'email')},
        ),
    ]
