# Generated by Django 6.0.5 on 2026-07-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic (25 USD)'), ('premium', 'Premium (40 USD)')], max_length=10, verbose_name='plan')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='montant')),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/%Y/%m/%d/', verbose_name="capture d'écran")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10, verbose_name='statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='events.event', verbose_name='événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'demande de paiement',
                'verbose_name_plural': 'demandes de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
