# Generated by Django 6.0.5 on 2026-07-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('total_guests_expected', models.PositiveIntegerField(default=0, help_text="Nombre total d'invités prévus (basé sur l'import Excel)", verbose_name='total invités prévus')),
                ('attendance_rate', models.PositiveIntegerField(default=75, help_text='Pourcentage estimé de personnes qui viendront', verbose_name='taux de présence (%)')),
                ('number_of_services', models.PositiveIntegerField(default=1, help_text='1 tournée = 1 boisson par personne', verbose_name='nombre de tournées')),
                ('currency', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', max_length=3, verbose_name='devise')),
                ('drink_forecast', models.JSONField(default=list, help_text='Liste des prévisions par boisson', verbose_name='prévisions par boisson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='events.event', verbose_name='événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'prévision',
                'verbose_name_plural': 'prévisions',
            },
        ),
        migrations.CreateModel(
            name='DrinkPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='supprimé')),
                ('drink_name', models.CharField(db_index=True, help_text='Ex: 33export, Vin rouge, Coca-Cola', max_length=100, verbose_name='nom de la boisson')),
                ('pieces_per_case', models.PositiveIntegerField(default=12, help_text='Nombre de bouteilles/pièces par casier/pack (ex: 12)', verbose_name='pièces par casier')),
                ('price_per_case', models.DecimalField(decimal_places=2, default=0, help_text="Prix d'un casier complet", max_digits=12, verbose_name='prix par casier')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_packagings', to='events.event', verbose_name='événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'conditionnement de boisson',
                'verbose_name_plural': 'conditionnements de boissons',
                'ordering': ['drink_name'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='expenses_dr_event_i_2e8188_idx'), models.Index(fields=['event', 'drink_name'], name='expenses_dr_event_i_a53beb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('event', 'drink_name'), name='unique_active_drink_packaging')],
            },
        ),
    ]
